### ISSUE TITLE
Include configuration and options

### ISSUE THREAD

**Issue by acheronfail** [acheronfail/apptivator#11]
Should store the configuration together with the serialised application entries.

Tasks:

- [x] (653797f) Store config in `~/Library/Preferences/Apptivator/config.json` or similar
- [x] (323fa9c) Add configuration options to preferences window 
- [x] Add configuration options and serialise them together in the same file
    - [x] (ae6139f) Apps should automatically hide when they lose focus (#9)
    - [x] (ae6139f) Open app if it's not running when shortcut pressed (#10) 
    - [x] (ae6139f) Hide application if it's active when shortcut fired
    - [x] Launch at login (#3)
